name: generate-pdf-folder-artifacts

on:
  pull_request: []
  push:
    branches:
     - master

jobs:
  GeneratePapers:
    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: "Training-Sustainable-Software-Dev"}
        - {name: "Remote-Work"}
        - {name: "RSE-Team-Management"}
    name: Generate ${{matrix.config.name}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Be sure to update to a release https://github.com/rseng/pdf-generator
      - name: Generate Paper
        uses: rseng/pdf-generator@master
        with:
          paper_markdown: WorkshopResources/WhitePapers/${{matrix.config.name}}/paper.md
          paper_outfile: WorkshopResources/WhitePapers/${{matrix.config.name}}.pdf
          bibtex: WorkshopResources/WhitePapers/${{matrix.config.name}}/paper.bib

          latex_template: templates/pandoc-scholar.latex
          #png_logo: templates/logo.png
          pdf_type: minimal

          #mapping_file: _events/sorse-mapping.txt
          #variables_file: _events/sorse-variables.txt
      - name: setup
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config user.name 'ginkgo-bot'
          git config user.email 'ginkgo.library@gmail.com'
          git add WorkshopResources/WhitePapers/${{matrix.config.name}}.pdf
          git commit -m "[bot] Update paper ${{matrix.config.name}}"
          git pull --rebase
          git push
